### ISSUE TITLE
[Bug]: tests/wordpress/WPCLICest.php won't be exectuted

### ISSUE THREAD

**Issue by hirasso** [sniccowp/sniccowp#223]
### Thanks for taking the time to fill out this bug report!"

- [X] I have searched the issue tracker for similar issues
- [X] I have verified that the issue is present when using the most recent version of the affected package(s)

### Which @snicco/* package(s) are the source of the bug?

better-wp-cli

### Is this a regression?

No

### Composer dependencies

```shell
n/a
```

### Current behaviour

tests/wordpress/WPCLICest.php contains a typo: **C**est.php instead of **T**est.php. The phpunit config file looks for the suffix `Test.php`. So the WPCLI Tests aren't executed if I'm right.

### Expected behaviour

The file and class should be named WPCLITest.php

### How to reproduce

n/a

### Possible solution

Rename the file

### Relevant log output

```shell
n/a
```

**Comment by calvinalkan** [comment]
tests inside `wordpress` are run with codeception and wp-browser currently, which uses `Cest`

Yeah... this monorepo uses two test runners...

Check the composer:test commands.

**Comment by hirasso** [comment]
oh my... tooling hell 😄 

Anyways, thanks for your quick reaction!!
